# Generated by Django 2.2.2 on 2019-07-06 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PerUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perOthers', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PerWorkExp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perProfession', models.CharField(max_length=50)),
                ('perJob', models.CharField(max_length=50)),
                ('perStart', models.DateField()),
                ('perEnd', models.DateField()),
                ('perSalary', models.IntegerField()),
                ('perDescription', models.TextField()),
                ('perComp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.CompUser')),
                ('perUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
        migrations.CreateModel(
            name='PerInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perEmail', models.EmailField(max_length=254)),
                ('perPwd', models.CharField(max_length=50)),
                ('perName', models.CharField(max_length=50)),
                ('perSex', models.BooleanField()),
                ('perBirth', models.DateField()),
                ('perHeadPath', models.CharField(max_length=50)),
                ('perCity', models.CharField(max_length=50)),
                ('perWorkStartTime', models.DateField()),
                ('perUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
        migrations.CreateModel(
            name='PerExpected',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perExpectedJob', models.CharField(max_length=50)),
                ('perExpectedProfession', models.CharField(max_length=50)),
                ('perExpectedSalary', models.IntegerField()),
                ('perUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
        migrations.CreateModel(
            name='PerEdu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perSchool', models.CharField(max_length=50)),
                ('perStatus', models.CharField(max_length=50)),
                ('perMajor', models.CharField(max_length=50)),
                ('perStudyStartTime', models.DateField()),
                ('perStudyEndTime', models.DateField()),
                ('perUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobName', models.CharField(max_length=50)),
                ('jobProfession', models.CharField(max_length=50)),
                ('jobSalary', models.IntegerField()),
                ('jobEdu', models.CharField(max_length=50)),
                ('jobExp', models.CharField(max_length=50)),
                ('jobNum', models.IntegerField()),
                ('jobSkill', models.CharField(max_length=50)),
                ('jobPublishedTime', models.DateField(auto_now_add=True)),
                ('jobIntro', models.TextField()),
                ('jobClickNum', models.IntegerField()),
                ('compUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.CompUser')),
            ],
        ),
        migrations.CreateModel(
            name='CompInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compFullName', models.CharField(max_length=50)),
                ('compLogoPath', models.CharField(max_length=50)),
                ('compVideoPath', models.CharField(max_length=50)),
                ('compProfession', models.CharField(max_length=50)),
                ('compCity', models.CharField(max_length=50)),
                ('compLoc', models.CharField(max_length=50)),
                ('compIntro', models.TextField()),
                ('compPwd', models.CharField(max_length=50)),
                ('compEmail', models.EmailField(max_length=254)),
                ('compUser', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.CompUser')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applyTime', models.DateTimeField(auto_now_add=True)),
                ('applyState', models.NullBooleanField()),
                ('applyJob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.Job')),
                ('applyPer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
    ]
