# Generated by Django 2.2.2 on 2019-07-07 11:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('RecruitApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ansContent', models.TextField()),
                ('ansCreateTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobCategory',
        ),
        migrations.RemoveField(
            model_name='job',
            name='jobCity',
        ),
        migrations.AddField(
            model_name='peruser',
            name='perLastClickMsgTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='LastTimeToClickMsg'),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobEdu',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobExp',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revContent', models.TextField()),
                ('revCreateTime', models.DateTimeField(auto_now_add=True)),
                ('revAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.Answer')),
                ('revAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quesTitle', models.CharField(max_length=50)),
                ('quesContent', models.TextField(default='')),
                ('quesReadCount', models.IntegerField(default=-1)),
                ('quesCreateTime', models.DateTimeField(auto_now_add=True)),
                ('quesAuthor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
        migrations.CreateModel(
            name='LikeList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likeCreateTime', models.DateTimeField(auto_now_add=True)),
                ('likeAnswer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.Answer')),
                ('likePerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
            ],
        ),
        migrations.CreateModel(
            name='CollectList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collCreateTime', models.DateTimeField(auto_now_add=True)),
                ('collPerUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser')),
                ('collQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.Question')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='ansAuthor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.PerUser'),
        ),
        migrations.AddField(
            model_name='answer',
            name='ansQuestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecruitApp.Question'),
        ),
    ]
